### ISSUE TITLE
Doens not seems to work on 32X8 panels

### ISSUE THREAD

**Issue by ewidance** [fabe1999/ScreenShare-WS2812b#1]
Hi, 

First of all, thanks for your job and the idea behind it. 

I just try with a 32X8 panel like that: https://fr.aliexpress.com/item/1005001835415125.html  It is configurered as is on arduino sketche:
```
const int width = 32;
const int height = 8;

//If you have a special kind of Matrix ore use more than one Tile you should change the settings here,
//For mor Information Visit the Adafruit NeoMatrix Guide: https://learn.adafruit.com/adafruit-neopixel-uberguide/neomatrix-library
Adafruit_NeoMatrix matrix = Adafruit_NeoMatrix(width, height, pin,
                            NEO_MATRIX_TOP     + NEO_MATRIX_LEFT +
                            NEO_MATRIX_COLUMNS  + NEO_MATRIX_ZIGZAG,
                            NEO_GRB            + NEO_KHZ800);
```

However, in the windows software, only a column of 8 pixel with,  is shown:
![2022-07-31 19_01_19-Screenshare_WS2812b _ Arduino 1 9 0-beta](https://user-images.githubusercontent.com/2135006/182037362-9f07454d-64ca-4c53-a6d7-381809601497.png)

It seems to be a bug with windows software. Any idea to fix it??

**Comment by fabe1999** [comment]
Hello, 
It looks like you have to resize your capture area. The problem at the moment is the software is trying to keep the aspect ratio of the picture to display it on your slim matrix. To keep the original aspect ratio there are black bars added left and right to your picture. It looks a bit wired because the 32*8 Pixels are shown in a square preview window. Try to resize the windows application until you can't see any black bars in the preview window. It should than light up every LED in your Matrix if you press the play button.
Please let me know if that works. 
Thanks for testing.

**Comment by ewidance** [comment]
Hi, I just tested and it does not works. When changing aspect ratio, communication seems to hang between PC dans display. I had to reset display, but got only 1 partial line instead of eight after reset. Played for a while with window resize with no luck.

**Comment by ewidance** [comment]
Additionnally, when resizing to 32X8, it's almost impossible to access play button.

**Comment by fabe1999** [comment]
That's odd. 
What board are you using to drive the Matrix? 
Unfortunately I don't have a 32*8 Matrix to test that. 
Could you do the following:
Start the Program, connect the Controller and press play without realizing the screen and take a Picture of the Matrix. After that resize the window to a frame as big as possible without black bars in the preview window. Take a Screenshot as well as a Picture of the Matrix and post both of them. Preferably use this Picture as a test: https://images.app.goo.gl/5PCvp8Y4VM3azjd76 (or something similar)

**Comment by ewidance** [comment]
HI. I'm using NodeMCU ESP32s.

I've simply lauch software and connected :
![IMG_3134](https://user-images.githubusercontent.com/2135006/182315645-70612bea-d708-4801-9804-962b6bb7cab8.jpg)

![2022-08-02 09_08_49-Google Image Result](https://user-images.githubusercontent.com/2135006/182315700-3dd7826d-061e-46eb-99e5-0678b69c9fee.png)

Then i resized smoothly the capture windows for adjusting aspect ratio. At a certain ratio, image on leds did not moved anymore (hanged).
![IMG_3135](https://user-images.githubusercontent.com/2135006/182315870-49ef0f25-515a-4292-af05-a4c698e8590b.jpg)

![2022-08-02 09_11_20-Google Image Result](https://user-images.githubusercontent.com/2135006/182315931-97db6564-96cb-4db2-81aa-c9360569a1fb.png)

Note after communication is lost, there's no more change on the led display, even if resising capture windows too inital size. I had to reset ESP to get back communication. 

If trying to reset esp when @32X8 aspect ratio, esp hangs immediately.

Hope this will helps.

**Comment by fabe1999** [comment]
Okay thanks, 
It looks like either the ESP is overwhelmed with the amount of Packages or something completely different. I will build a matrix with these dimensions and try to narrow it down. 
You could try reduce the FPS maybe that helps. (Go to the settings and change the "Picture refresh time in ms" to a higher number)

**Comment by ewidance** [comment]
It did not helped. I went @200ms then 500 ms and it hangs exactly at the same moment (see previous picture). When hanged, restart windows app does not helps, communication is brocken. If not relauching windows app, but resising to a square aspect ratio (as launched) and resetting ESP helps. Communication is restoring automatically. 

It seems definitely to be a problem in ESP code (buffer overrun? out of memory?). Code itself is relatively tiny, so i don't suspect it's about code size, but more on variable allocation of buffer overrun.

**Comment by ewidance** [comment]
Strtemp too big???

**Comment by ewidance** [comment]
I've made some tests with MatrixGFXDemo to verify leds arrangement. It's ok with
```
Adafruit_NeoMatrix *matrix = new Adafruit_NeoMatrix(32, 8, 
  13,
  NEO_MATRIX_TOP    + NEO_MATRIX_LEFT +
  NEO_MATRIX_COLUMNS + NEO_MATRIX_ZIGZAG,
  NEO_GRB            + NEO_KHZ800);
```

**Comment by fabe1999** [comment]
I just threw together a 32*8 matrix and could recreate your Problem. I'm looking into it on the weekend. For the meantime you could change the Orientation of your Matrix
`const int width = 32;
const int height = 8;`

That worked perfectly fine (remember to change the rest of the Matrix configuration according to your LED layout)

**Comment by ewidance** [comment]
Your right, works fine in 8x32 (vertical), even with 100ms.  Cooool ! 

Note: If you plan to modify code to fix the 'horizontal bug', it would be cool to :
- add brightness setting in windows software (and a brightness command in the firmware) because when driving big matrix, it can be hot :). Neomatrix brightness command is matrix.setBrightness(u_int);
- Manage controls resize efficiently or don't manage at all (fixed size buttons) for play pause resize change settings

**Comment by fabe1999** [comment]
Well that was an easy fix.
I updated the Arduino code in the Bugfix branch to allow bigger udp Packet sizes.
The previous code just stopped after 255 characters.
Now the package size is calculated so it should work with way bigger sizes as well.
I'm also working on your suggested features. But the bug itself should be fixed.

Could you test that again?

**Comment by ewidance** [comment]
I updated Arduino code today, and works  fine. However, i d'ont have visual studio installed, so can't compile & test windows code. Would you please publish installer in bugfix? I'll test other functionnalities added during the weekend.

**Comment by fabe1999** [comment]
I already merged it back to the main branch. You can find the updated installer as a release (v1.1.0)

**Comment by ewidance** [comment]
Coool!  thanks again!

**Comment by ewidance** [comment]
Sorry to bother, but widows setup dir contains only Windows-Setup.vdproj file... No exe or MSI.

**Comment by fabe1999** [comment]
Yes it's now a release:
[Setup v1.1.0](https://github.com/fabe1999/ScreenShare-WS2812b/releases/tag/v1.1.0)
